name: Deploy Breast Cancer App to Heroku

on:
  push:
    branches:
      - main  # Runs on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com login=oauth password=$HEROKU_API_KEY" > ~/.netrc
          echo "machine git.heroku.com login=oauth password=$HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc
          heroku auth:whoami  # Verify authentication

      - name: Set Heroku Git Remote
        run: |
          git remote remove heroku || echo "No existing Heroku remote"
          heroku git:remote -a breast-cancer-app-predictor
          git remote -v  # Verify remote setup

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Ensure dependencies are installed

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "GitHub Actions Deployment" || echo "No changes to commit"
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/breast-cancer-app-predictor.git main --force  # 🔥 FIXED!

      - name: Verify Deployment
        run: |
          heroku ps  # Check if the app is running
          heroku open  # Open the deployed app URL (optional)
